language: r
warnings_are_errors: true

before_script:
  - sudo apt-get install -y ghostscript
  - sudo apt-get install -y qpdf

r_build_args: '--compact-vignettes="gs+qpdf"'

r_check_args: '--as-cran'

r:
  - release
  - devel
