library(ppjsdm)

context("gibbsm")

# # Generated by a 2-dimensional Sobol sequence sobol(200, dim = 2)
# # Printed with paste0(sprintf("%.8f", s[, 2]), collapse = ", ")
# x_test <- c(0.50000000, 0.75000000, 0.25000000, 0.37500000, 0.87500000, 0.62500000,
#             0.12500000, 0.18750000, 0.68750000, 0.93750000, 0.43750000, 0.31250000,
#             0.81250000, 0.56250000, 0.06250000, 0.09375000, 0.59375000, 0.84375000,
#             0.34375000, 0.46875000, 0.96875000, 0.71875000, 0.21875000, 0.15625000,
#             0.65625000, 0.90625000, 0.40625000, 0.28125000, 0.78125000, 0.53125000,
#             0.03125000, 0.04687500, 0.54687500, 0.79687500, 0.29687500, 0.42187500,
#             0.92187500, 0.67187500, 0.17187500, 0.23437500, 0.73437500, 0.98437500,
#             0.48437500, 0.35937500, 0.85937500, 0.60937500, 0.10937500, 0.07812500,
#             0.57812500, 0.82812500, 0.32812500, 0.45312500, 0.95312500, 0.70312500,
#             0.20312500, 0.14062500, 0.64062500, 0.89062500, 0.39062500, 0.26562500,
#             0.76562500, 0.51562500, 0.01562500, 0.02343750, 0.52343750, 0.77343750,
#             0.27343750, 0.39843750, 0.89843750, 0.64843750, 0.14843750, 0.21093750,
#             0.71093750, 0.96093750, 0.46093750, 0.33593750, 0.83593750, 0.58593750,
#             0.08593750, 0.11718750, 0.61718750, 0.86718750, 0.36718750, 0.49218750,
#             0.99218750, 0.74218750, 0.24218750, 0.17968750, 0.67968750, 0.92968750,
#             0.42968750, 0.30468750, 0.80468750, 0.55468750, 0.05468750, 0.03906250,
#             0.53906250, 0.78906250, 0.28906250, 0.41406250, 0.91406250, 0.66406250,
#             0.16406250, 0.22656250, 0.72656250, 0.97656250, 0.47656250, 0.35156250,
#             0.85156250, 0.60156250, 0.10156250, 0.07031250, 0.57031250, 0.82031250,
#             0.32031250, 0.44531250, 0.94531250, 0.69531250, 0.19531250, 0.13281250,
#             0.63281250, 0.88281250, 0.38281250, 0.25781250, 0.75781250, 0.50781250,
#             0.00781250, 0.01171875, 0.51171875, 0.76171875, 0.26171875, 0.38671875,
#             0.88671875, 0.63671875, 0.13671875, 0.19921875, 0.69921875, 0.94921875,
#             0.44921875, 0.32421875, 0.82421875, 0.57421875, 0.07421875, 0.10546875,
#             0.60546875, 0.85546875, 0.35546875, 0.48046875, 0.98046875, 0.73046875,
#             0.23046875, 0.16796875, 0.66796875, 0.91796875, 0.41796875, 0.29296875,
#             0.79296875, 0.54296875, 0.04296875, 0.05859375, 0.55859375, 0.80859375,
#             0.30859375, 0.43359375, 0.93359375, 0.68359375, 0.18359375, 0.24609375,
#             0.74609375, 0.99609375, 0.49609375, 0.37109375, 0.87109375, 0.62109375,
#             0.12109375, 0.08984375, 0.58984375, 0.83984375, 0.33984375, 0.46484375,
#             0.96484375, 0.71484375, 0.21484375, 0.15234375, 0.65234375, 0.90234375,
#             0.40234375, 0.27734375, 0.77734375, 0.52734375, 0.02734375, 0.01953125,
#             0.51953125, 0.76953125, 0.26953125, 0.39453125, 0.89453125, 0.64453125,
#             0.14453125, 0.20703125)
#
# y_test <- c(0.50000000, 0.25000000, 0.75000000, 0.37500000, 0.87500000, 0.12500000,
#             0.62500000, 0.31250000, 0.81250000, 0.06250000, 0.56250000, 0.18750000,
#             0.68750000, 0.43750000, 0.93750000, 0.46875000, 0.96875000, 0.21875000,
#             0.71875000, 0.09375000, 0.59375000, 0.34375000, 0.84375000, 0.15625000,
#             0.65625000, 0.40625000, 0.90625000, 0.28125000, 0.78125000, 0.03125000,
#             0.53125000, 0.26562500, 0.76562500, 0.01562500, 0.51562500, 0.14062500,
#             0.64062500, 0.39062500, 0.89062500, 0.07812500, 0.57812500, 0.32812500,
#             0.82812500, 0.45312500, 0.95312500, 0.20312500, 0.70312500, 0.23437500,
#             0.73437500, 0.48437500, 0.98437500, 0.35937500, 0.85937500, 0.10937500,
#             0.60937500, 0.42187500, 0.92187500, 0.17187500, 0.67187500, 0.04687500,
#             0.54687500, 0.29687500, 0.79687500, 0.39843750, 0.89843750, 0.14843750,
#             0.64843750, 0.02343750, 0.52343750, 0.27343750, 0.77343750, 0.21093750,
#             0.71093750, 0.46093750, 0.96093750, 0.33593750, 0.83593750, 0.08593750,
#             0.58593750, 0.11718750, 0.61718750, 0.36718750, 0.86718750, 0.49218750,
#             0.99218750, 0.24218750, 0.74218750, 0.30468750, 0.80468750, 0.05468750,
#             0.55468750, 0.17968750, 0.67968750, 0.42968750, 0.92968750, 0.13281250,
#             0.63281250, 0.38281250, 0.88281250, 0.25781250, 0.75781250, 0.00781250,
#             0.50781250, 0.44531250, 0.94531250, 0.19531250, 0.69531250, 0.07031250,
#             0.57031250, 0.32031250, 0.82031250, 0.35156250, 0.85156250, 0.10156250,
#             0.60156250, 0.22656250, 0.72656250, 0.47656250, 0.97656250, 0.03906250,
#             0.53906250, 0.28906250, 0.78906250, 0.41406250, 0.91406250, 0.16406250,
#             0.66406250, 0.33203125, 0.83203125, 0.08203125, 0.58203125, 0.20703125,
#             0.70703125, 0.45703125, 0.95703125, 0.01953125, 0.51953125, 0.26953125,
#             0.76953125, 0.39453125, 0.89453125, 0.14453125, 0.64453125, 0.17578125,
#             0.67578125, 0.42578125, 0.92578125, 0.30078125, 0.80078125, 0.05078125,
#             0.55078125, 0.48828125, 0.98828125, 0.23828125, 0.73828125, 0.11328125,
#             0.61328125, 0.36328125, 0.86328125, 0.06640625, 0.56640625, 0.31640625,
#             0.81640625, 0.44140625, 0.94140625, 0.19140625, 0.69140625, 0.25390625,
#             0.75390625, 0.00390625, 0.50390625, 0.12890625, 0.62890625, 0.37890625,
#             0.87890625, 0.41015625, 0.91015625, 0.16015625, 0.66015625, 0.03515625,
#             0.53515625, 0.28515625, 0.78515625, 0.22265625, 0.72265625, 0.47265625,
#             0.97265625, 0.34765625, 0.84765625, 0.09765625, 0.59765625, 0.19921875,
#             0.69921875, 0.44921875, 0.94921875, 0.32421875, 0.82421875, 0.07421875,
#             0.57421875, 0.38671875)
#
# configuration_test <- ppjsdm::Configuration(x = x_test, y = y_test, types = rep(1:3, length.out = length(x_test)))
#
# test_that("gibbsm returns correct parameters for Geyer potentials potentials", {
#   ntypes <- 3
#   short_range <- matrix(0.02, ntypes, ntypes)
#   medium_range <- matrix(0.04, ntypes, ntypes)
#   long_range <- matrix(0.08, ntypes, ntypes)
#   covariates <- list(x = function(x, y) x)
#   max_dummy <- 1e3
#   dummy_factor <- 1e6
#   saturation <- 2
#
#   set.seed(1)
#   fit <- gibbsm(configuration_test,
#                 short_range = short_range,
#                 medium_range = medium_range,
#                 long_range = long_range,
#                 fitting_package = "glm",
#                 max_dummy = max_dummy,
#                 covariates = covariates,
#                 dummy_factor = dummy_factor,
#                 saturation = saturation,
#                 model = "Geyer",
#                 medium_range_model = "Geyer")
#
#   # Printed with paste0("matrix(c(", paste0(sprintf("%.30f", as.vector(fit$coefficients$alpha)), collapse = ", "), "), ntypes, ntypes)")
#   target_alpha <- matrix(c(-7.445278701969089141243784979451, -0.177490467508480381786384327825,
#                            -0.194336419680457644920679172174, -0.177490467508480381786384327825,
#                            -0.525330874165940375775107895606, -0.295688660651177492866281681927,
#                            -0.194336419680457644920679172174, -0.295688660651177492866281681927,
#                            -0.230690945936496583090757894752), ntypes, ntypes)
#   # Printed with paste0("matrix(c(", paste0(sprintf("%.30f", as.vector(fit$coefficients$gamma)), collapse = ", "), "), ntypes, ntypes)")
#   target_gamma <- matrix(c(0.204369778254962275454431619437, 0.037432830406825670643833348095,
#                            -0.009244095277088073756011077364, 0.037432830406825670643833348095,
#                            0.216321729397492362734212179021, -0.053754001257007209824134719156,
#                            -0.009244095277088073756011077364, -0.053754001257007209824134719156,
#                            0.395687240437798515291234480173), ntypes, ntypes)
#   # Printed with paste0(sprintf("%.30f", as.vector(fit$coefficients$beta0)), collapse = ", ")
#   target_beta0 <- c(3.934771893501741057974641080364, 3.976276802325434012175264797406, 3.729457114683529361798264289973)
#
#   expect_equal(as.vector(fit$coefficients$alpha), as.vector(target_alpha))
#   expect_equal(as.vector(fit$coefficients$gamma), as.vector(target_gamma))
#   expect_equal(as.vector(fit$coefficients$beta0), as.vector(target_beta0))
# })
#
# test_that("gibbsm returns correct parameters for Exponential/Geyer potentials", {
#   short_range <- matrix(0.01, 2, 2)
#   medium_range <- matrix(0.02, 2, 2)
#   long_range <- matrix(0.04, 2, 2)
#   covariates <- list(x = function(x, y) x)
#   max_dummy <- 1e3
#   dummy_factor <- 1e6
#   saturation <- 2
#
#   set.seed(1)
#   z <- ppjsdm::rppp(lambda = c(1e2, 1e2))
#
#   fit <- gibbsm(z, short_range = short_range,
#                 medium_range = medium_range,
#                 long_range = long_range,
#                 fitting_package = "glm",
#                 max_dummy = max_dummy,
#                 covariates = covariates,
#                 dummy_factor = dummy_factor,
#                 saturation = saturation,
#                 model = "exponential",
#                 medium_range_model = "Geyer")
#
#   target_alpha <- cbind(c(0.36336369048743522025546326403855346143245697021484, -0.19446700039060069165053334927506512030959129333496),
#                         c(-0.19446700039060069165053334927506512030959129333496, 0.27457522734498557293036924420448485761880874633789))
#   target_gamma <- cbind(c(-0.08297137548644326066060727953299647197127342224121, 0.08329905314773396185490383913929690606892108917236),
#                         c(0.08329905314773396185490383913929690606892108917236, -0.04220028235639199098994112091531860642135143280029))
#   target_beta0 <- c(4.57327077246616475747487129410728812217712402343750, 4.72239072452669272905723119038157165050506591796875)
#
#   expect_equal(as.vector(fit$coefficients$alpha), as.vector(target_alpha))
#   expect_equal(as.vector(fit$coefficients$gamma), as.vector(target_gamma))
#   expect_equal(as.vector(fit$coefficients$beta0), as.vector(target_beta0))
# })
#
# test_that("gibbsm returns correct parameters for Exponential/Half exponential potentials", {
#   short_range <- matrix(0.01, 2, 2)
#   medium_range <- matrix(0.02, 2, 2)
#   long_range <- matrix(0.04, 2, 2)
#   covariates <- list(x = function(x, y) x)
#   max_dummy <- 1e3
#   dummy_factor <- 1e6
#   saturation <- 2
#
#   set.seed(1)
#   z <- ppjsdm::rppp(lambda = c(1e2, 1e2))
#
#   # Exponential/Half exponential potentials
#   fit <- gibbsm(z, short_range = short_range,
#                 medium_range = medium_range,
#                 long_range = long_range,
#                 fitting_package = "glm",
#                 max_dummy = max_dummy,
#                 covariates = covariates,
#                 dummy_factor = dummy_factor,
#                 saturation = saturation,
#                 model = "exponential",
#                 medium_range_model = "half_exponential")
#
#   target_alpha <- cbind(c(0.46316221468203372380045834688644390553236007690430, -0.12841035124783206633480858727125450968742370605469),
#                         c(-0.12841035124783206633480858727125450968742370605469, 0.26250071426500326543518326616322156041860580444336))
#   target_gamma <- cbind(c(-0.35514469623914096674255347352300304919481277465820, 0.04449345621518227544832768671767553314566612243652),
#                         c(0.04449345621518227544832768671767553314566612243652, -0.02976090796946117764121275683919520815834403038025))
#   target_beta0 <- c(4.83942274113594095297230524010956287384033203125000, 4.72348555684051074621265797759406268596649169921875)
#
#   expect_equal(as.vector(fit$coefficients$alpha), as.vector(target_alpha))
#   expect_equal(as.vector(fit$coefficients$gamma), as.vector(target_gamma))
#   expect_equal(as.vector(fit$coefficients$beta0), as.vector(target_beta0))
# })
#
# test_that("gibbsm returns correct parameters for Exponential/Square exponential potentials", {
#   short_range <- matrix(0.01, 2, 2)
#   medium_range <- matrix(0.02, 2, 2)
#   long_range <- matrix(0.04, 2, 2)
#   covariates <- list(x = function(x, y) x)
#   max_dummy <- 1e3
#   dummy_factor <- 1e6
#   saturation <- 2
#
#   set.seed(1)
#   z <- ppjsdm::rppp(lambda = c(1e2, 1e2))
#
#   fit <- gibbsm(z, short_range = short_range,
#                 medium_range = medium_range,
#                 long_range = long_range,
#                 fitting_package = "glm",
#                 max_dummy = max_dummy,
#                 covariates = covariates,
#                 dummy_factor = dummy_factor,
#                 saturation = saturation,
#                 model = "exponential",
#                 medium_range_model = "square_exponential")
#
#   target_alpha <- cbind(c(0.50757549646651989316836761645390652120113372802734, -0.28208707564593760164228797293617390096187591552734),
#                         c(-0.28208707564593760164228797293617390096187591552734, 0.33349752459166975837590030096180271357297897338867))
#   target_gamma <- cbind(c(-0.20753037003541913163573440215259324759244918823242, 0.14356938938182947640420650259329704567790031433105),
#                         c(0.14356938938182947640420650259329704567790031433105, -0.09404490341622943894162034439432318322360515594482))
#   target_beta0 <- c(4.59347691764322263452413608320057392120361328125000, 4.71948357859354583609956534928642213344573974609375)
#
#   expect_equal(as.vector(fit$coefficients$alpha), as.vector(target_alpha))
#   expect_equal(as.vector(fit$coefficients$gamma), as.vector(target_gamma))
#   expect_equal(as.vector(fit$coefficients$beta0), as.vector(target_beta0))
# })

test_that("gibbsm works with infinite saturation for Geyer potentials potentials", {
  ntypes <- 4
  short_range <- matrix(0.01, ntypes, ntypes)
  medium_range <- matrix(0.02, ntypes, ntypes)
  long_range <- matrix(0.04, ntypes, ntypes)
  max_dummy <- 1e3
  dummy_factor <- 1e6
  saturation <- 1e6

  set.seed(1)
  z <- ppjsdm::rppp(lambda = rep(1e2, ntypes))

  set.seed(1)
  fit_large <- suppressWarnings(gibbsm(z, short_range = short_range,
                                       medium_range = medium_range,
                                       long_range = long_range,
                                       fitting_package = "glm",
                                       max_dummy = max_dummy,
                                       dummy_factor = dummy_factor,
                                       saturation = 1e6,
                                       model = "Geyer",
                                       medium_range_model = "Geyer"))

  set.seed(1)
  fit_infinite <- suppressWarnings(gibbsm(z, short_range = short_range,
                                          medium_range = medium_range,
                                          long_range = long_range,
                                          fitting_package = "glm",
                                          max_dummy = max_dummy,
                                          dummy_factor = dummy_factor,
                                          saturation = Inf,
                                          model = "Geyer",
                                          medium_range_model = "Geyer"))

  expect_equal(as.vector(fit_large$coefficients$alpha[[1]]), as.vector(fit_infinite$coefficients$alpha[[1]]))
  expect_equal(as.vector(fit_large$coefficients$gamma), as.vector(fit_infinite$coefficients$gamma))
  expect_equal(as.vector(fit_large$coefficients$beta0), as.vector(fit_infinite$coefficients$beta0))
})

test_that("gibbsm works with infinite saturation for Exponential/Geyer potentials", {
  ntypes <- 4
  short_range <- matrix(0.01, ntypes, ntypes)
  medium_range <- matrix(0.02, ntypes, ntypes)
  long_range <- matrix(0.04, ntypes, ntypes)
  max_dummy <- 1e3
  dummy_factor <- 1e6
  saturation <- 1e6

  set.seed(1)
  z <- ppjsdm::rppp(lambda = rep(1e2, ntypes))

  set.seed(1)
  fit_large <- gibbsm(z, short_range = short_range,
                      medium_range = medium_range,
                      long_range = long_range,
                      fitting_package = "glm",
                      max_dummy = max_dummy,
                      dummy_factor = dummy_factor,
                      saturation = 1e6,
                      model = "exponential",
                      medium_range_model = "Geyer")

  set.seed(1)
  fit_infinite <- gibbsm(z, short_range = short_range,
                         medium_range = medium_range,
                         long_range = long_range,
                         fitting_package = "glm",
                         max_dummy = max_dummy,
                         dummy_factor = dummy_factor,
                         saturation = Inf,
                         model = "exponential",
                         medium_range_model = "Geyer")

  expect_equal(as.vector(fit_large$coefficients$alpha[[1]]), as.vector(fit_infinite$coefficients$alpha[[1]]))
  expect_equal(as.vector(fit_large$coefficients$gamma), as.vector(fit_infinite$coefficients$gamma))
  expect_equal(as.vector(fit_large$coefficients$beta0), as.vector(fit_infinite$coefficients$beta0))
})

test_that("gibbsm works with infinite saturation for Exponential/Half exponential potentials", {
  ntypes <- 4
  short_range <- matrix(0.01, ntypes, ntypes)
  medium_range <- matrix(0.02, ntypes, ntypes)
  long_range <- matrix(0.04, ntypes, ntypes)
  max_dummy <- 1e3
  dummy_factor <- 1e6
  saturation <- 1e6

  set.seed(1)
  z <- ppjsdm::rppp(lambda = rep(1e2, ntypes))

  set.seed(1)
  fit_large <- gibbsm(z, short_range = short_range,
                      medium_range = medium_range,
                      long_range = long_range,
                      fitting_package = "glm",
                      max_dummy = max_dummy,
                      dummy_factor = dummy_factor,
                      saturation = 1e6,
                      model = "exponential",
                      medium_range_model = "half_exponential")

  set.seed(1)
  fit_infinite <- gibbsm(z, short_range = short_range,
                         medium_range = medium_range,
                         long_range = long_range,
                         fitting_package = "glm",
                         max_dummy = max_dummy,
                         dummy_factor = dummy_factor,
                         saturation = Inf,
                         model = "exponential",
                         medium_range_model = "half_exponential")

  expect_equal(as.vector(fit_large$coefficients$alpha[[1]]), as.vector(fit_infinite$coefficients$alpha[[1]]))
  expect_equal(as.vector(fit_large$coefficients$gamma), as.vector(fit_infinite$coefficients$gamma))
  expect_equal(as.vector(fit_large$coefficients$beta0), as.vector(fit_infinite$coefficients$beta0))
})

test_that("gibbsm works with infinite saturation for Exponential/Square exponential potentials", {
  ntypes <- 4
  short_range <- matrix(0.01, ntypes, ntypes)
  medium_range <- matrix(0.02, ntypes, ntypes)
  long_range <- matrix(0.04, ntypes, ntypes)
  max_dummy <- 1e3
  dummy_factor <- 1e6
  saturation <- 1e6

  set.seed(1)
  z <- ppjsdm::rppp(lambda = rep(1e2, ntypes))

  set.seed(1)
  fit_large <- gibbsm(z, short_range = short_range,
                      medium_range = medium_range,
                      long_range = long_range,
                      fitting_package = "glm",
                      max_dummy = max_dummy,
                      dummy_factor = dummy_factor,
                      saturation = 1e6,
                      model = "exponential",
                      medium_range_model = "square_exponential")

  set.seed(1)
  fit_infinite <- gibbsm(z, short_range = short_range,
                         medium_range = medium_range,
                         long_range = long_range,
                         fitting_package = "glm",
                         max_dummy = max_dummy,
                         dummy_factor = dummy_factor,
                         saturation = Inf,
                         model = "exponential",
                         medium_range_model = "square_exponential")

  expect_equal(as.vector(fit_large$coefficients$alpha[[1]]), as.vector(fit_infinite$coefficients$alpha[[1]]))
  expect_equal(as.vector(fit_large$coefficients$gamma), as.vector(fit_infinite$coefficients$gamma))
  expect_equal(as.vector(fit_large$coefficients$beta0), as.vector(fit_infinite$coefficients$beta0))
})
