# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_papangelou_cpp <- function(configuration, x, y, model, medium_range_model, alpha, beta0, beta, gamma, covariates, short_range, medium_range, long_range, saturation, type = 1L, mark = 1.0) {
    .Call(`_ppjsdm_compute_papangelou_cpp`, configuration, x, y, model, medium_range_model, alpha, beta0, beta, gamma, covariates, short_range, medium_range, long_range, saturation, type, mark)
}

compute_vcov <- function(configuration, dummy, window, covariates, model, medium_range_model, short_range, medium_range, long_range, saturation, rho, theta, regressors, data_list, estimate_alpha, estimate_gamma, debug, nthreads, npoints, dummy_distribution, mark_range) {
    .Call(`_ppjsdm_compute_vcov`, configuration, dummy, window, covariates, model, medium_range_model, short_range, medium_range, long_range, saturation, rho, theta, regressors, data_list, estimate_alpha, estimate_gamma, debug, nthreads, npoints, dummy_distribution, mark_range)
}

#' Check if a configuration contains duplicates.
#'
#' @param configuration Configuration.
#' @export
#' @useDynLib ppjsdm, .registration = TRUE
#' @import Rcpp
has_duplicates <- function(configuration) {
    .Call(`_ppjsdm_has_duplicates`, configuration)
}

make_default_model_parameters <- function(alpha, beta0, covariates, beta, gamma, short_range, medium_range, long_range, types, default_number_types) {
    .Call(`_ppjsdm_make_default_model_parameters`, alpha, beta0, covariates, beta, gamma, short_range, medium_range, long_range, types, default_number_types)
}

prepare_gibbsm_data <- function(configuration_list, window, covariates, model, medium_range_model, short_range, medium_range, long_range, saturation, mark_range, max_dummy, min_dummy, dummy_factor, estimate_alpha, estimate_gamma, nthreads, debug, dummy_distribution, type_names) {
    .Call(`_ppjsdm_prepare_gibbsm_data`, configuration_list, window, covariates, model, medium_range_model, short_range, medium_range, long_range, saturation, mark_range, max_dummy, min_dummy, dummy_factor, estimate_alpha, estimate_gamma, nthreads, debug, dummy_distribution, type_names)
}

rbinomialpp_cpp <- function(window, n, nsim, types, drop, mark_range) {
    .Call(`_ppjsdm_rbinomialpp_cpp`, window, n, nsim, types, drop, mark_range)
}

rgibbs_cpp <- function(window, alpha, beta0, covariates, beta, gamma, short_range, medium_range, long_range, saturation, steps, nsim, types, model, medium_range_model, drop, mark_range, starting_configuration) {
    .Call(`_ppjsdm_rgibbs_cpp`, window, alpha, beta0, covariates, beta, gamma, short_range, medium_range, long_range, saturation, steps, nsim, types, model, medium_range_model, drop, mark_range, starting_configuration)
}

rppp_cpp <- function(window, lambda, nsim, types, drop, mark_range) {
    .Call(`_ppjsdm_rppp_cpp`, window, lambda, nsim, types, drop, mark_range)
}

rstratpp_cpp <- function(window, delta_x, delta_y, nsim, types, drop, mark_range) {
    .Call(`_ppjsdm_rstratpp_cpp`, window, delta_x, delta_y, nsim, types, drop, mark_range)
}

#' Show the authorised short range models.
#'
#' @export
#' @useDynLib ppjsdm, .registration = TRUE
#' @import Rcpp
show_short_range_models <- function() {
    invisible(.Call(`_ppjsdm_show_short_range_models`))
}

#' Show the authorised medium range models.
#'
#' @export
#' @useDynLib ppjsdm, .registration = TRUE
#' @import Rcpp
show_medium_range_models <- function() {
    invisible(.Call(`_ppjsdm_show_medium_range_models`))
}

