# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute the delta of the phi-dispersion of a marked configuration.
#'
#' @param configuration The configuration.
#' @param location Point to be added.
#' @param type Type of point to be added.
#' @param number_types Number of different types.
#' @param model String representing the model to simulate from. At the moment, either "identity", "Strauss" or "Geyer".
#' @param radius Radius of interaction.
#' @export
#' @useDynLib ppjsdm
#' @import Rcpp
compute_delta_phi_dispersion <- function(configuration, location, type, number_types, model = "identity", radius = 0) {
    .Call('_ppjsdm_compute_delta_phi_dispersion', PACKAGE = 'ppjsdm', configuration, location, type, number_types, model, radius)
}

#' Check if a configuration contains duplicates.
#'
#' @param configuration Configuration.
#' @export
#' @useDynLib ppjsdm
#' @import Rcpp
has_duplicates <- function(configuration) {
    .Call('_ppjsdm_has_duplicates', PACKAGE = 'ppjsdm', configuration)
}

#' Sample a binomial point processes
#'
#' @param window Simulation window. Default is a Rectangle window [0, 1]^2.
#' @param n A vector representing the number of points of each types of the multipoint binomial point processes.
#' Default is a vector of same size as types, filled with ones.
#' @param nsim Number of samples to generate. Default is 1.
#' @param types Types of the points. Default is a vector (type1, type2, ...) of same size as n.
#' @param drop If nsim = 1 and drop = TRUE, the result will be a Configuration, rather than a list containing a Configuration.
#' Default is TRUE.
#' @export
#' @useDynLib ppjsdm
#' @import Rcpp
rbinomialpp <- function(window = NULL, n = NULL, nsim = 1L, types = NULL, drop = TRUE) {
    .Call('_ppjsdm_rbinomialpp', PACKAGE = 'ppjsdm', window, n, nsim, types, drop)
}

#' Sample a multivariate Gibbs point processes
#'
#' @param window Simulation window.
#' @param alpha Repulsion matrix. Default is a square matrix of same size as types, filled with zeroes.
#' @param lambda A vector representing the intensities of the point processes.
#' Default is a vector of same size as types, filled with ones.
#' @param nu A vector representing the dispersion of the number of points.
#' Default is a vector of same size as types, filled with ones.
#' @param radius Interaction radius. Default is zero.
#' @param steps Number of steps in the Metropolis algorithm. Default is 30000.
#' @param nsim Number of samples to generate. Default is 1.
#' @param types Types of the points. Default is a vector (type1, type2, ...) of same size as n.
#' @param model String representing the model to simulate from. At the moment, either "identity", "Strauss", "Geyer" or "neighbour",
#' with default beign "identity".
#' @param drop If nsim = 1 and drop = TRUE, the result will be a Configuration, rather than a list containing a Configuration. Default is TRUE.
#' @export
#' @useDynLib ppjsdm
#' @import Rcpp
rmultigibbs <- function(window = NULL, alpha = NULL, lambda = NULL, nu = NULL, radius = 0, steps = 30000L, nsim = 1L, types = NULL, model = "identity", drop = TRUE) {
    .Call('_ppjsdm_rmultigibbs', PACKAGE = 'ppjsdm', window, alpha, lambda, nu, radius, steps, nsim, types, model, drop)
}

#' Sample a Poisson point processes
#'
#' @param window Simulation window. Default is a Rectangle window [0, 1]^2.
#' @param lambda A vector representing the intensities of the multipoint Poisson point processes.
#' Default is a vector of same size as types, filled with ones.
#' @param nsim Number of samples to generate. Default is 1.
#' @param types Types of the points. Default is a vector (type1, type2, ...) of same size as n.
#' @param drop If nsim = 1 and drop = TRUE, the result will be a Configuration, rather than a list containing a Configuration.
#' Default is TRUE.
#' @export
#' @useDynLib ppjsdm
#' @import Rcpp
rppp <- function(window = NULL, lambda = NULL, nsim = 1L, types = NULL, drop = TRUE) {
    .Call('_ppjsdm_rppp', PACKAGE = 'ppjsdm', window, lambda, nsim, types, drop)
}

