# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute Papangelou conditional intensity of the model.
#'
#' @param configuration Configuration.
#' @param x Coordinates along the x-axis of the points at which to evaluate the Papangelou conditional intensity.
#' @param y Coordinates along the x-axis of the points at which to evaluate the Papangelou conditional intensity.
#' @param type Type of the point (as an integer >= 1).
#' @param model String representing the model to use. You can check the currently authorised models with a call to `show_models()`.
#' @param medium_range_model String representing the medium range model to use. You can check the currently authorised models with a call to `show_medium_range_models()`.
#' @param alpha Short range repulsion matrix.
#' @param lambda A vector representing the intensities of the point processes.
#' @param beta Coefficients related to covariates.
#' @param gamma Medium range repulsion matrix.
#' @param covariates Covariates.
#' @param short_range Short range interaction radii.
#' @param medium_range Medium range interaction radii.
#' @param long_range Long range interaction radii.
#' @param saturation Saturation parameter.
#' @param max_points Maximum number of points.
#' @param mark Mark of the point to add.
#' @export
#' @useDynLib ppjsdm
#' @import Rcpp
compute_papangelou <- function(configuration, x, y, type, model, medium_range_model, alpha, lambda, beta, gamma, covariates, short_range, medium_range, long_range, saturation, max_points, mark = 1.0) {
    .Call('_ppjsdm_compute_papangelou', PACKAGE = 'ppjsdm', configuration, x, y, type, model, medium_range_model, alpha, lambda, beta, gamma, covariates, short_range, medium_range, long_range, saturation, max_points, mark)
}

#' Check if a configuration contains duplicates.
#'
#' @param configuration Configuration.
#' @export
#' @useDynLib ppjsdm
#' @import Rcpp
has_duplicates <- function(configuration) {
    .Call('_ppjsdm_has_duplicates', PACKAGE = 'ppjsdm', configuration)
}

prepare_gibbsm_data <- function(configuration_list, window, covariates, traits, model, medium_range_model, short_range, medium_range, long_range, saturation, mark_range, approximate) {
    .Call('_ppjsdm_prepare_gibbsm_data', PACKAGE = 'ppjsdm', configuration_list, window, covariates, traits, model, medium_range_model, short_range, medium_range, long_range, saturation, mark_range, approximate)
}

rbinomialpp_cpp <- function(window, n, nsim, types, drop, mark_range) {
    .Call('_ppjsdm_rbinomialpp_cpp', PACKAGE = 'ppjsdm', window, n, nsim, types, drop, mark_range)
}

rgibbs_cpp <- function(window, alpha, lambda, covariates, beta, gamma, short_range, medium_range, long_range, saturation, max_points, steps, nsim, types, model, medium_range_model, drop, mark_range) {
    .Call('_ppjsdm_rgibbs_cpp', PACKAGE = 'ppjsdm', window, alpha, lambda, covariates, beta, gamma, short_range, medium_range, long_range, saturation, max_points, steps, nsim, types, model, medium_range_model, drop, mark_range)
}

rppp_cpp <- function(window, lambda, nsim, types, drop, mark_range) {
    .Call('_ppjsdm_rppp_cpp', PACKAGE = 'ppjsdm', window, lambda, nsim, types, drop, mark_range)
}

#' Show the authorised short range models.
#'
#' @export
#' @useDynLib ppjsdm
#' @import Rcpp
show_short_range_models <- function() {
    invisible(.Call('_ppjsdm_show_short_range_models', PACKAGE = 'ppjsdm'))
}

#' Show the authorised medium range models.
#'
#' @export
#' @useDynLib ppjsdm
#' @import Rcpp
show_medium_range_models <- function() {
    invisible(.Call('_ppjsdm_show_medium_range_models', PACKAGE = 'ppjsdm'))
}

