#' Display a trace plot of the underlying Metropolis-Hastings algorithm used
#' to obtain a sample of a `ppjsdm` point process.
#'
#' @param x A simulated ppjsdm object, usually obtained from running `rgibbs` with the Metropolis-Hastings algorithm.
#' @param type Display trace plot corresponding to this type.
#' @export
trace_plot <- function(x, type = 1) {

  number_points <- attr(x, "number_points")
  if(is.null(number_points)) {
    stop("The supplied object does not have a number_points attribute. This likely means that it was not generated by a ppjsdm function using the Metropolis-Algorithm.")
  }

  initial_type <- type

  # If the user supplies a string as the type, they want to evaluate the trace plot
  # of that type.
  if(is.character(type)) {
    type <- which(type == levels(types(x)))[1]
  }

  plot(sapply(number_points, function(y) y[type]),
       xlab = "Number of steps in the Metropolis-Hastings algorithm",
       ylab = paste0("Number of points of type ", initial_type))
}
